### PR TITLE
Update to 19021

### LINKED ISSUE #13: Error 6 with 18.10.0 Edify binary and current updater-script
Using `update-binary` from `18.10.0-sibon-280f64b0-ota.zip` causes the following error in TWRP:

```
Installing zip file '/sideload/package.zip'
Updater process ended with ERROR: 6"
```

However, it works just great with the 18.04.1 one (`fp2-sibon-18.04.1-ota-userdebug.zip`). This may mean our `updater-script` is not compatible with some new syntax for Oreo's [Edify](https://source.android.com/devices/tech/ota/nonab/inside_packages), so we should keep this in mind for future releases.

As a temporary measure, we can just release it with 18.04.1's Edify.

### PR DESCRIPTION
**Pull request by Ingo-FP-Angel**
Use 19.02.1 firmware files.
Adjust syntax to check for device compatibility to work with the Android 7 update-binary.

Fixes #13

### CODE REVIEW

**Review by z3ntu — APPROVED** [review]
LGTM

sha256sum:
`0762fc8beb98317a6a56ee5a98045143fe485355a75e959816828af9847d3577  build/modem.zip`

**Review by Roboe — CHANGES_REQUESTED** [review]
(It's approved, sorry for the mess)

LGTM too, Good job fixing #13, :+1: 

sha256sum is `24da92b6d931bbbf93fd9195b0f7e5bc16d4da07a55a3877b1e15de534c2b06d` for me. Seems to be a mismatch, @z3ntu, but we can look further to fix this on #9 with your latest commits there.

**Review by Roboe — APPROVED** [review]

**Comment by Roboe** [comment]
I've observed there's a new binary on the OTA package (but not on the MANUAL one, weird) that we don't conver in our script:

```
package_extract_file("firmware-update/sdi.mbn", "/dev/block/platform/msm_sdcc.1/by-name/sdi");
```

Should we include it too?

**Comment by Roboe** [comment]
I've added the file and resorted to use only the OTA package for both Edify interpreter and firmware binaries (it's usually irrelevant, but in this case only the OTA package has the `sdi` binary).

@Ingo-FP-Angel ~~May you please enable me to push commits to this PR? [There should be a checkbox at the right of this comment](https://github.blog/2016-09-07-improving-collaboration-with-forks/).~~ Nevermind, I'll merge this and then push my changes to the `master` branch.

**Review by Roboe — APPROVED** [review]

**Comment by Ingo-FP-Angel** [comment]
Do you mean the "Allow edits from maintainers." checkbox? That's already ticked.

Edit: forgot to reload before posting ;-)

**Comment by Roboe** [comment]
Yes, I meant that checkbox. Well, it didn't work for some reason, :man_shrugging: 

Thanks again for the PR! :)

**Pull request merged**
