### PR TITLE
update to 18.01.1

### PR DESCRIPTION
**Pull request by m4lvin**

### CODE REVIEW

**Review by z3ntu — APPROVED** [review]
LGTM

**Comment by jannispinter** [comment]
Thank you! I'll merge it, but the modem firmware has not changed, so it is not really necessary to install this release. Sorry that it took me so long.

**Comment by m4lvin** [comment]
No problem. But I am now confused: Is this repository here only about the modem firmware or the whole boot.img which also contains the bootloader? My motivation for getting the new boot.img was to follow the instructions from @z3ntu for getting postmarketOS running and that only worked with 18.01.1. See also https://wiki.postmarketos.org/wiki/Fairphone_2_(fairphone-fp2)#Installation

**Comment by jannispinter** [comment]
I was not aware of that patch, the modem.zip updates the proprietary Qualcomm components (modem firmware, trust zone firmware and other files including the bootloader). Usually we update the modem.zip only if the modem firmware has changed (which hasn't happened since november).

I'm going to update this for every release from now on.

**Pull request merged**
